
import './globals.css'
import { ReactNode } from 'react'
import RootLayout from './RootLayout' // تأكد من المسار الصحيح
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'MovieForge',
  description: 'Generated by create next app',
  icons: '/popcorn.png',
}

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  )
}
